version: "2"
services:
  node:
    image: "node:10"
    user: "node"
    build:
      context: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 8500:8500
      - 8501:8501
    command: sh -cl 'npm install --verbose && npm run build'
