import path from 'path';
import * as React from 'react';
import * as express from 'express';
import { renderToString } from 'react-dom/server';
import { StaticRouter as Router } from 'react-router-dom';
import { Store } from 'redux';
import { Provider } from 'react-redux';
import { HelmetProvider } from 'react-helmet-async';
import { ServerStyleSheet } from 'styled-components';
import { ChunkExtractor } from '@loadable/server';
import IntlProvider from '../../shared/i18n/IntlProvider';
import App from '../../shared/App';
import Html from '../components/HTML';
import paths from '../../../config/paths';

// This is the stats file generated by webpack loadable plugin
const statsFile = path.join(paths.clientBuild, 'static/loadable-stats.json');
const extractor = new ChunkExtractor({ statsFile, entrypoints: ['bundle'] });
const helmetContext = {};
const routerContext = {};

const serverRenderer: any = () => (
    req: express.Request & { store: Store },
    res: express.Response
) => {
    const sheet = new ServerStyleSheet(); // <-- creating out stylesheet
    const SSRApp = () => (
        <Provider store={res.locals.store}>
            <Router location={req.url} context={routerContext}>
                <IntlProvider>
                    <HelmetProvider context={helmetContext}>
                        <App />
                    </HelmetProvider>
                </IntlProvider>
            </Router>
        </Provider>
    );
    const jsx = extractor.collectChunks(<SSRApp />);
    const content = renderToString(sheet.collectStyles(jsx));
    const state = JSON.stringify(res.locals.store.getState());
    const html = renderToString(
        <Html
            styles={extractor.getStyleElements()}
            links={extractor.getLinkElements()}
            helmetContext={helmetContext}
            scripts={extractor.getScriptElements()}
            state={state}
        >
            {content}
        </Html>
    );
    return res.send('<!doctype html>' + html);
};

export default serverRenderer;
